[package]
name = "homemaker"
version = "0.0.1"
authors = ["Matt Weller <hellmitre@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dirs = "2.0"
shellexpand = "2.0.0"
symlink = "0.1.0"
solvent = "0.8.2"
indicatif = ">=0.15.0"
console = ">=0.12.0"
