[[file]]
file = 'tmux.conf'
source = '~/dotfiles/.tmux.conf'
destination = '~'
method = 'symlink'

[[file]]
file = 'fish'
source = '~/dotfiles/.config/fish'
destination = '~/.config/fish'
method = 'symlink'
